
app:
  deployment:
    container:
      name: eva
      image: ghcr.io/nw-bi/eva
      tag: latest
      imagePullPolicy: Always
      ports:
        containerPort: 8000
      envFrom: []
      env: []
  appName: eva
parameter:
  appHost: eva.bidm.nw.de
  appNamespace: eva
  ingress:
    oauth:
      enable: true
      enabled_groups: ['NW-BI-KUB']
middleware:
  names: []


