apiVersion: v1
data:
  API_TOKEN_FRISBII_HK: {{ .Values.secrets.token_frisbii_hk | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: token-frisbii-hk
  namespace: dagster
---
apiVersion: v1
data:
  API_TOKEN_FRISBII_NW: {{ .Values.secrets.token_frisbii_nw | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: token-frisbii-nw
  namespace: dagster