apiVersion: v1
data:
  haenjes_sftp_user: {{ .Values.secrets.haenjes_sftp_user | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: haenjes-sftp-user
  namespace: dagster
---
apiVersion: v1
data:
  haenjes_sftp_pw: {{ .Values.secrets.haenjes_sftp_pw | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: haenjes-sftp-pw
  namespace: dagster