apiVersion: v1
data:
  dargel_sftp_user: {{ .Values.secrets.dargel_sftp_user | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: dargel-sftp-user
  namespace: dagster
---
apiVersion: v1
data:
  dargel_sftp_pw: {{ .Values.secrets.dargel_sftp_pw | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: dargel-sftp-pw
  namespace: dagster