apiVersion: v1
data:
  aschendorff_sftp_server: {{ .Values.secrets.frisbii_sftp_server }}
kind: Secret
metadata:
  creationTimestamp: null
  name: frisbii-sftp-server
  namespace: dagster
---

apiVersion: v1
data:
  aschendorff_sftp_user: {{ .Values.secrets.frisbii_sftp_user }}
kind: Secret
metadata:
  creationTimestamp: null
  name: frisbii-sftp-user
  namespace: dagster
---

apiVersion: v1
data:
  aschendorff_sftp_pw: {{ .Values.secrets.frisbii_sftp_pw }}
kind: Secret
metadata:
  creationTimestamp: null
  name: frisbii-sftp-pw
  namespace: dagster
