apiVersion: v1
data:
  sovendus_sftp_user: {{ .Values.secrets.sovendus_sftp_user | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: sovendus-sftp-user
  namespace: dagster
---
apiVersion: v1
data:
  sovendus_sftp_pw: {{ .Values.secrets.sovendus_sftp_pw | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: sovendus-sftp-pw
  namespace: dagster