apiVersion: v1
data:
  heim_sftp_user: {{ .Values.secrets.heim_sftp_user | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: heim-sftp-user
  namespace: dagster
---
apiVersion: v1
data:
  heim_sftp_pw: {{ .Values.secrets.heim_sftp_pw | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: heim-sftp-pw
  namespace: dagster