apiVersion: v1
data:
  dpag_sftp_user: {{ .Values.secrets.dpag_sftp_user | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: dpag-sftp-user
  namespace: dagster
---
apiVersion: v1
data:
  dpag_sftp_pw: {{ .Values.secrets.dpag_sftp_pw | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: dpag-sftp-pw
  namespace: dagster