apiVersion: v1
data:
  dialogcrm_sftp_server: {{ .Values.secrets.dialogcrm_sftp_server }}
kind: Secret
metadata:
  creationTimestamp: null
  name: dialogcrm-sftp-server
  namespace: dagster
---
apiVersion: v1
data:
  dialogcrm_sftp_user: {{ .Values.secrets.dialogcrm_sftp_user | b64enc}}
kind: Secret
metadata:
  creationTimestamp: null
  name: dialogcrm-sftp-user
  namespace: dagster
---
apiVersion: v1
data:
  dialogcrm_sftp_pw: {{ .Values.secrets.dialogcrm_sftp_pw | b64enc}}
kind: Secret
metadata:
  creationTimestamp: null
  name: dialogcrm-sftp-pw
  namespace: dagster