apiVersion: v1
data:
  zbs_herden_sftp_user: {{ .Values.secrets.zbs_herden_sftp_user | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: zbs-herden-sftp-user
  namespace: dagster
---
apiVersion: v1
data:
  zbs_herden_sftp_pw: {{ .Values.secrets.zbs_herden_sftp_pw | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: zbs-herden-sftp-pw
  namespace: dagster