secrets:
  basicAuthFile:
      htpasswd: kuchen
  dockerPullSecret: kuchen
  dbtSnowflakeUsername_stage: kuchen
  dbtSnowflakeUsername: kuchen
  dbtSnowflakePassword_stage: kuchen
  dbtSnowflakePassword: kuchen
  dbtSnowflakeRole_stage: kuchen
  dbtSnowflakeRole: kuchen
  dbt_target_stage: kuchen
  dbt_target: kuchen
  dagster_target_stage: kuchen
  dagster_target: kuchen
  fkWebcrallerListings_stage: kuchen
  fkWebcrallerListings: kuchen
  driveBigqueryKey_stage: kuchen
  driveBigqueryKey: kuchen
  fkCmsRssFeed_stage: kuchen
  fkCmsRssFeed: kuchen
  selligentCPOIncoiceID_stage: kuchen
  selligentCPOIncoiceID: kuchen
  X_VERTRIEB_USER: kuchen
  X_VERTRIEB_PW: kuchen
  dlsbinwdevStorageKey_stage: kuchen
  dlsbinwdevStorageKey: kuchen
  dlsbinwdevStorage_stage: kuchen
  dlsbinwdevStorage: kuchen
  shopware_api_user: kuchen
  shopware_api_token: kuchen
  blob_nwbidls_account_key: kuchen
  blob_nwbidls_account_name: kuchen
  mail_user: kuchen
  mail_pw: kuchen
  mail_bi: kuchen
  mail_server: kuchen
  mssql_dagster_user: kuchen
  mssql_dagster_pw: kuchen
  viva_db: kuchen
  davicon_db: kuchen
  viva_dll_db: kuchen
  viva_server: kuchen
  avs_sftp_servername: kuchen
  avs_sftp_pw: kuchen
  avs_sftp_benutzer: kuchen
  crm_ftp_user: kuchen
  crm_ftp_pw: kuchen
  crm_ftp_server: kuchen
  selligent_sftp_server: kuchen
  selligent_sftp_user: kuchen
  selligent_sftp_pw: kuchen
  humboldt_sftp_pw: kuchen
  humboldt_sftp_user: kuchen
  humboldt_sftp_server: kuchen
  matomo_server_pw: kuchen
  sftp_die_glocke_pw: kuchen
  sftp_mip_server: kuchen
  ivw_user: kuchen
  ivw_pw: kuchen
  sftp_die_glocke: kuchen
  snowflake_p8_key: kuchen
  crm_exp_ftp_pw: kuchen
  crm_exp_ftp_user: kuchen
  crm_exp_ftp_server: kuchen
  upscore_api_token: kuchen
  adx_ftp_user: kuchen
  adx_ftp_pw: kuchen
  adx_ftp_server: kuchen
  humboldt_leserreisen_sftp_user: kuchen
  humboldt_leserreisen_sftp_pw: kuchen
  humboldt_leserreisen_sftp_server: kuchen
  hanseat_cloud_user: kuchen
  hanseat_cloud_pw: kuchen
  hanseat_cloud_server: kuchen
  SELLIGENT_API_KEY: kuchen
  SELLIGENT_API_KEY_BI: kuchen
  SELLIGENT_SDC_CLIENT_ID: kuchen
  SELLIGENT_SDC_SECRET: kuchen
  SELLIGENT_SDC_ACCOUNT_ID_BULK: kuchen
  SELLIGENT_SDC_ACCOUNT_ID_TRANSACTIONAL: kuchen
  SELLIGENT_SDC_CUSTOMER: kuchen
  BDL_SERVER: kuchen
  BDL_USER: kuchen
  BDL_PW: kuchen
  DIR_SAP_FI_EPAY: kuchen
  X_SERVER_SAP_FI_EPAY: kuchen
  mip_jira_server: kuchen
  mip_jira_user: kuchen
  mip_jira_pw: kuchen
  aschendorff_sftp_server: kuchen
  aschendorff_sftp_user: kuchen
  aschendorff_sftp_pw: kuchen
  token_frisbii_hk: kuchen
  token_frisbii_nw: kuchen
  qualifio_sftp_server: kuchen
  qualifio_sftp_user: kuchen
  qualifio_sftp_pw: kuchen
parameters:
  dagsterHost: kuchen-host